targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            "^lib/providers/{{}}.dart": "lib/providers/generated/{{}}.g.dart"
            "^lib/models/{{}}.dart": "lib/models/generated/{{}}.g.dart"
            "^lib/services/{{}}.dart": "lib/services/generated/{{}}.g.dart"
      freezed:freezed:
        options:
          union_key: "type"
          union_value_case: "snake"
          map: false
          when: false
          copy_with: true
          to_string: false
          equals: true
          build_extensions:
            "^lib/models/{{}}.dart": "lib/models/generated/{{}}.freezed.dart"

      drift_dev:drift_dev:
        options:
          write_from_json_string_constructor: true
          named_parameters: true
          store_date_time_values_as_text: true
