name: tickme
description: A simple time tracking app. Powered by AI. Verified by human.

publish_to: none
version: 0.1.0

environment:
  sdk: ^3.4.4

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2 # Added intl dependency for date formatting

  fl_chart: ^0.71.0 # Added fl_chart for potential pie charts

  shared_preferences: ^2.3.3 # Added shared_preferences for data persistence

  cupertino_icons: ^1.0.8 # Only required if you use Cupertino (iOS style) icons


dev_dependencies:
  flutter_test:
    sdk: flutter
