name: tickme
description: A simple time tracking app. Powered by AI. Verified by human.

publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  fl_chart: ^0.71.0
  shared_preferences: ^2.3.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  json_serializable: ^6.8.0
  uuid: ^4.5.1
  hooks_riverpod: ^2.6.1
  go_router: ^15.1.2
  json_annotation: ^4.9.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
